language: python

python:
  - 3.6

git:
  submodules: false

before_install:
  - git submodule update --init --recursive

jobs:
  include:
    - stage: deploy
      if: tag IS present
      script: plugin_ci/release/release.sh
